# Ejercicio 1: Introducción a Recuperación de Información

## Objetivo de la práctica
- Entender el problema de **buscar información** en colecciones de texto.
- Comprender por qué se necesita un **índice invertido** en recuperación de información.
- Programar una primera solución manual y luego optimizarla con un índice.
- Evaluar la mejora en tiempos de búsqueda cuando usamos estructuras adecuadas.

## Parte 1: Búsqueda lineal en documentos

### Actividad
1. Se te proporcionará un dataset con reviews de películas.
2. Escribe una función que:
   - Lea todos los documentos.
   - Busque una palabra ingresada por el usuario.
   - Muestre en qué documentos aparece la palabra.

In [3]:
import pandas as pd
import numpy as np

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

In [63]:
df = pd.read_csv("/kaggle/input/imdb-dataset-of-50k-movie-reviews/IMDB Dataset.csv")

#path = '../data/'
#df = pd.read_csv(path + 'IMDB Dataset.csv.zip', compression='zip')
df

review sentiment
0      One of the other reviewers has mentioned that ...  positive
1      A wonderful little production. <br /><br />The...  positive
2      I thought this was a wonderful way to spend ti...  positive
3      Basically there's a family where a little boy ...  negative
4      Petter Mattei's "Love in the Time of Money" is...  positive
...                                                  ...       ...
49995  I thought this movie did a down right good job...  positive
49996  Bad plot, bad dialogue, bad acting, idiotic di...  negative
49997  I am a Catholic taught in parochial elementary...  negative
49998  I'm going to have to disagree with the previou...  negative
49999  No one expects the Star Trek movies to be high...  negative

[50000 rows x 2 columns]

In [12]:
# creacion de funcion que Lea todos los documentos.
def buscar(docs, query, na=False):
	mask = docs.str.contains(query)
	result = docs[mask]
	return result

In [35]:
# A continuacion se busca una palabra ingresada por el usuario.
resultados = buscar(df['review'], 'wonderful')

In [38]:
# a continuacion se muestra en qué documentos aparece la palabra seleccionada previamente
print(resultados.index.values)

[    1     2    29 ... 49935 49938 49941]


## Parte 2: Construcción de un índice invertido

### Actividad
1. Escribe un programa que:
   - Recorra todos los documentos.
   - Construya un **índice invertido**, es decir, un diccionario donde:
     - Cada palabra clave apunta a una lista de documentos donde aparece.

2. Escribe una nueva función de búsqueda que:
   - Consulte directamente el índice para encontrar los documentos relevantes.
   - Sea mucho más rápida que la búsqueda lineal.

In [ ]:
# funcion que recorre todos los documentos y construya un índice invertido
# la funcion itera sobre las primeras 1000 filas
def recorrer_palabras_columna(doc, review):
    diccionario_palabras = {}

    for i, fila in doc[review].dropna().head(1000).items():
        palabras = str(fila).split()
        for palabra in palabras:
            palabra = palabra.lower().strip(".,!¡¿?:;\"'()[]")
            if palabra not in diccionario_palabras:
                diccionario_palabras[palabra] = [i]
            else:
                if i not in diccionario_palabras[palabra]:
                    diccionario_palabras[palabra].append(i)
    
    return diccionario_palabras

In [ ]:
# se crea un dic1 para el diccionario del primer dataFrame
dic1 = recorrer_palabras_columna(df, 'review')

In [ ]:
# se muestran los índices en donde se encuentra la palabra 'wonderful' en el primer dataFrame
print(dic1['wonderful'])

## Parte 3: Evaluación de tiempos de búsqueda
### Actividad

1. Realiza la búsqueda de varias palabras usando:
      -  Corpus pequeño.
      -  Corpus grande.
2. Mide el tiempo de ejecución:
      -  Para búsqueda lineal.
      -  Para búsqueda usando índice invertido.
      -  Grafica o presenta los resultados en una tabla comparativa.

In [11]:
df_large = pd.read_csv("/kaggle/input/clapper-massive-rotten-tomatoes-movies-and-reviews/rotten_tomatoes_movie_reviews.csv")
#df_large = pd.read_csv(path + 'rotten_tomatoes_movie_reviews.csv.zip', compression='zip')
df_large

id   reviewId creationDate  \
0                                  beavers    1145982   2003-05-23   
1                               blood_mask    1636744   2007-06-02   
2        city_hunter_shinjuku_private_eyes    2590987   2019-05-28   
3        city_hunter_shinjuku_private_eyes    2558908   2019-02-14   
4                       dangerous_men_2015    2504681   2018-08-29   
...                                    ...        ...          ...   
1444958              thor_love_and_thunder  102706151   2022-07-05   
1444959              thor_love_and_thunder  102706150   2022-07-05   
1444960              thor_love_and_thunder  102706149   2022-07-05   
1444961              thor_love_and_thunder  102706148   2022-07-05   
1444962              thor_love_and_thunder  102706147   2022-07-05   

              criticName  isTopCritic originalScore reviewState  \
0        Ivan M. Lincoln        False         3.5/4       fresh   
1          The Foywonder        False           1/5      rotten   
2           Reuben Baron        False           NaN       fresh   
3            Matt Schley        False         2.5/5      rotten   
4              Pat Padua        False           NaN       fresh   
...                  ...          ...           ...         ...   
1444958  Christie Cronan        False          7/10       fresh   
1444959     Ian Sandwell        False           4/5       fresh   
1444960   Lauren LaMagna        False          8/10       fresh   
1444961        Jake Cole         True           1/4      rotten   
1444962      Roger Moore        False         2.5/4       fresh   

                        publicatioName  \
0        Deseret News (Salt Lake City)   
1                        Dread Central   
2                                  CBR   
3                          Japan Times   
4                                DCist   
...                                ...   
1444958               Raising Whasians   
1444959                    Digital Spy   
1444960              Next Best Picture   
1444961                 Slant Magazine   
1444962                   Movie Nation   

                                                reviewText scoreSentiment  \
0        Timed to be just long enough for most youngste...       POSITIVE   
1        It doesn't matter if a movie costs 300 million...       NEGATIVE   
2        The choreography is so precise and lifelike at...       POSITIVE   
3        The film's out-of-touch attempts at humor may ...       NEGATIVE   
4        Its clumsy determination is endearing and some...       POSITIVE   
...                                                    ...            ...   
1444958  Solid but not totally sold&#44; Thor&#58; Ragn...       POSITIVE   
1444959  Thor&#58; Love and Thunder is the most enterta...       POSITIVE   
1444960  &quot;Thor&#58; Love and Thunder&quot; is a st...       POSITIVE   
1444961  Across Taika Waititi&#8217;s film&#44; a war a...       NEGATIVE   
1444962  It&#8217;s the jokes that make it&#44; with th...       POSITIVE   

                                                 reviewUrl  
0        http://www.deseretnews.com/article/700003233/B...  
1        http://www.dreadcentral.com/index.php?name=Rev...  
2        https://www.cbr.com/city-hunter-shinjuku-priva...  
3        https://www.japantimes.co.jp/culture/2019/02/0...  
4        http://dcist.com/2015/11/out_of_frame_dangerou...  
...                                                    ...  
1444958  https://raisingwhasians.com/thor-love-and-thun...  
1444959  https://www.digitalspy.com/movies/a40496050/th...  
1444960  https://www.nextbestpicture.com/thor-love-and-...  
1444961  https://www.slantmagazine.com/film/thor-love-a...  
1444962  https://rogersmovienation.com/2022/07/05/movie...  

[1444963 rows x 11 columns]

In [59]:
def buscar(docs, query, na=False):
	mask = docs.str.contains(query, na=na, regex=False)
	result = docs[mask]
	return result

In [23]:
buscar(df_large['reviewText'], 'woderful').index.values

array([678810])

In [20]:
indice_invertido = {'a': buscar(df_large['reviewText'], 'a').index.values,
'matter': buscar(df_large['reviewText'], 'matter').index.values,
'wonderful': buscar(df_large['reviewText'], 'wonderful').index.values
}
indice_invertido['wonderful']

array([    487,    1014,    1029, ..., 1444392, 1444746, 1444920])